### ISSUE TITLE
SUGGESTION: Remove Horizontal Scrollbar for Hot Keys Window

### ISSUE THREAD

**Issue by David-Hobson** [NathanCoit/4GP6Capstone#100]
It seems that the Hot Keys window on the options screen has a horizontal scrollbar. This scrollbar is not useful since there is nothing to scroll to, the vertical scrollbar alone should work fine.

**Comment by NathanCoit** [comment]
Horizontal scrolling/dragging disabled for hotkey menu. Horizontal scroll bar auto shows when items in scroll view are too wide. Scaled hot key settors so that horizontal scroll bar does not appear.
