### ISSUE TITLE
ISSUE: Defeated Enemy God and Game Resets

### ISSUE THREAD

**Issue by David-Hobson** [NathanCoit/4GP6Capstone#101]
This is similar to the buildings disappearing after battle issue. However, it seems that the entire game resets, my village gets moved, my stats get reset, and my buildings also disappear. The enemies buildings also face the same issue.

**Comment by NathanCoit** [comment]
New game flag was not being set to false once a new game had finished being created. Fixed in c3edf9509559a75d8135094cd10efedcd537d070
