### ISSUE TITLE
ISSUE: Building Close to Edge Limits Construction Area for Other Players

### ISSUE THREAD

**Issue by David-Hobson** [NathanCoit/4GP6Capstone#104]
If you put your buildings very close to the edge of your area, you can limit the area that the enemies are allowed to build in, giving you an immediate advantage. Enemies can also do this you.

**Comment by NathanCoit** [comment]
Scaled building objects down. Territory intrusion should not affect player as much since they have more room and intruding buildings intrude on a much smaller scale.
![image](https://user-images.githubusercontent.com/26461233/52387200-3f0f4f00-2a57-11e9-8bc4-bd46f39432e3.png)
