### ISSUE TITLE
ISSUE: Entering Long Name Causes Text to Overlap

### ISSUE THREAD

**Issue by David-Hobson** [NathanCoit/4GP6Capstone#108]
When entering a name for the god, if the name is too long, the text for the buildings will overlap. This can be prevented by limiting the name size. Screen shot below:
![image](https://user-images.githubusercontent.com/15710591/50606082-6ab87b80-0e92-11e9-85e2-778449fac3cf.png)

**Comment by NathanCoit** [comment]
Imposed character limit on God Name 19ab1241270a81c7939c737b83bcde1d80c32a27
