### ISSUE TITLE
Suggestions: Have Tooltips

### ISSUE THREAD

**Issue by pavlearezina** [NathanCoit/4GP6Capstone#126]
Have a tooltip when hovering over the stats of your god (the stats shown in the top left corner) since it is hard to understand what influences those numbers and why they are important.

**Comment by NathanCoit** [comment]
Tooltips implemented in 4d6ccb3a486e43d6d422a09a0dbe3b9b09866822 and 325c87832054949333d6a1152153f088b83b7a1a.
Leaving issue open until tooltips are added to more areas of the game.
