### ISSUE TITLE
Issue: No feedback after saving settings. 

### ISSUE THREAD

**Issue by nicolaikozel** [NathanCoit/4GP6Capstone#128]
There should be some kind of confirmation badge, text, icon, etc so the user knows their settings have been changed successfully. Since exiting to the main menu currently discards them, it makes the user feel uneasy about exiting because they aren't sure if there settings were saved or not and are afraid of losing them.

**Comment by NathanCoit** [comment]
Made it so once you click "Save Settings", you are redirected back to the Main Menu/ Pause Menu. Added confirmation when trying to close with unsaved changes.
