### ISSUE TITLE
Issue: Quit button during pause menu is misleading. (Think it closes menu)

### ISSUE THREAD

**Issue by nicolaikozel** [NathanCoit/4GP6Capstone#131]
The quit button in the pause menu while in game is misleading. There should be a close menu button as well so that players are not confused and accidentally quit the game without saving (since there is no auto save or prompt).

**Comment by NathanCoit** [comment]
Changed wording from "Quit" to "Quit to Title" 8fff813b1c1298f0736b603c0977e4ff48cab081
