### ISSUE TITLE
Issue #2: Game freezes after creating 4 objectives

### ISSUE THREAD

**Issue by ButterJX** [NathanCoit/4GP6Capstone#138]
In duck gods, after placed 4 objectives. The camera freezes. Had to press ESC twice to move the camera.

**Comment by NathanCoit** [comment]
Probable cause was opening the tier rewards UI as a duck god as pointed out in other issues, which was broken. Opening tier reward menu disables camera movement but had an issue and did not bring up UI. Pressing escape re enabled camera movement as intended.
