### ISSUE TITLE
<Issues> The save game function will create another blank copy of the state.

### ISSUE THREAD

**Issue by Codhog** [NathanCoit/4GP6Capstone#147]
The “save game” function will create 2 states with same name for “load game”.
However, one of the earlier state is the same as the new game.

**Comment by NathanCoit** [comment]
On starting a new game, a save file is created to ensure there is always a last save file for the player to load in case the player loses/dies in combat mode. This save is more of a safety net. Implementing the choice to overwrite old save files should make this more clear and clear up confusion about multiple saves/what save file is being used.
