### ISSUE TITLE
Connect Combat and Management Mode

### ISSUE THREAD

**Issue by SullivanStobo** [NathanCoit/4GP6Capstone#15]

**Comment by NathanCoit** [comment]
Created a GameInfo script and prefab that persists through scenes. At the start of the scene check for existence with
```GameObject GameInfoObject = GameObject.Find("GameInfo");
        if (GameInfoObject != null)
        {
            // Found a gameinfo object, load values
            gameInfo = GameInfoObject.GetComponent<GameInfo>();
```
then pull the values from the public variables on the GameInfo script attached.
Once combat is done, set any variables back into the gameinfo object that need to be passed back to management mode.

**Comment by harrilau** [comment]
Kinda works? We can look at it tomorrow before the presentation.

**Comment by SullivanStobo** [comment]
We're mostly there, just need to double check tomorrow

**Comment by SullivanStobo** [comment]
I think we're done this
