### ISSUE TITLE
Issue #2(Bug): Territory intrusion

### ISSUE THREAD

**Issue by lawlbit** [NathanCoit/4GP6Capstone#157]
When I started a new game, I selected the duck gods and when I went into the game world I the mushroom god's shrine was in my territory.
![image](https://user-images.githubusercontent.com/15020935/50984497-0fa90900-14d0-11e9-8be8-2c8d08106f5d.png)

**Comment by NathanCoit** [comment]
Scaled building objects down. Territory intrusion should not affect player as much since they have more room and intruding buildings intrude on a much smaller scale.
![image](https://user-images.githubusercontent.com/26461233/52387200-3f0f4f00-2a57-11e9-8bc4-bd46f39432e3.png)
