### ISSUE TITLE
Issue: Camera still moves even if game is in background

### ISSUE THREAD

**Issue by sma7560** [NathanCoit/4GP6Capstone#170]
Running 1280x720 Windowed mode.
Even when the game is unfocused and there is something else on top of the game (through dragging a window or alt-tabbing), the camera's edge scrolling still triggers. This does not occur when the game is minimized.

**Comment by NathanCoit** [comment]
Fixed in 716e157fa3e3a6801563366ee5e555c01cbe8bc0
