### ISSUE TITLE
Suggestion: Please at least darken the main menu background from bright pure white

### ISSUE THREAD

**Issue by Chaozs** [NathanCoit/4GP6Capstone#180]

**Comment by NathanCoit** [comment]
Fixed in e9f62ae68df1e420be6f37550b1cb040ec22e1a4

**Comment by Chaozs** [comment]
Where: Main menu
Issue: main menu background is pure white, and very bright and hard on the eyes
Suggestion: Change background to some color shade that is easier on the eye.
