### ISSUE TITLE
Bug: Hotkeys box is slightly smaller than the items inside of it

### ISSUE THREAD

**Issue by Chaozs** [NathanCoit/4GP6Capstone#181]
You cannot see the very top and very bottom of the options inside hotkeys

**Comment by NathanCoit** [comment]
Fixed in c53cb4254ae37fadaef743a6f819728a4f281125

**Comment by Chaozs** [comment]
Where: menu screen, settings
Issue:
>the hotkeys "box" surrounding the hot-key option buttons inside of it, is too small for the items inside of it.
>Results in the top and bottom of the items inside hotkeys box not visible.
