### ISSUE TITLE
Suggestions: Show borders for all enemy AI lands.

### ISSUE THREAD

**Issue by Chaozs** [NathanCoit/4GP6Capstone#186]

**Comment by NathanCoit** [comment]
Intended feature is for each god to have a unique texture for their territory. Once this is implemented, and all gods have unique building models, distinguishing territories should be clear.

**Comment by Chaozs** [comment]
Where: In-game
Issue: You cannot tell where each god's land is on the map
Suggested solution: Show borders on where each god's land ends
