### ISSUE TITLE
SUGGESTION: Options Menu Hot Key Box Dimensions

### ISSUE THREAD

**Issue by SusanSuY** [NathanCoit/4GP6Capstone#54]
In the Options menu, the "Hot Keys" box seems to have no white space at the top and bottom (looks awkward). May want to add some white space at the top and bottom. Also, left and right scroll do not seem necessary for this box.

**Comment by NathanCoit** [comment]
Added padding to the top and bottom of hotkeys section. Removed horizontal scroll bar and disabled horizontal movement.
