### ISSUE TITLE
ISSUE: Able to Build Structures On the Line Border

### ISSUE THREAD

**Issue by SusanSuY** [NathanCoit/4GP6Capstone#55]
**Issue:** The player can build structures that are on top of the border's line, resulting in part of the structure being outside the border.

This appears a little strange since structures aren't fully contained within the building space.

**Comment by NathanCoit** [comment]
Scaled building objects down. Building on territory lines in much less noticeable as the scale is lowered.
![image](https://user-images.githubusercontent.com/26461233/52387200-3f0f4f00-2a57-11e9-8bc4-bd46f39432e3.png)
