### ISSUE TITLE
ISSUE: Settings Not Saved from In-Game Options Menu

### ISSUE THREAD

**Issue by SusanSuY** [NathanCoit/4GP6Capstone#57]
**ISSUE:** Settings are not saved from the in-game options menu.

**Steps to Reproduce:**
- Open the game
- Start a new game
- Press "ESC" key to get to in-game menu
- Click "Options"
- Change volume and graphics settings
- Click "Save Settings"
- Click "Close"
- Click "Options" again
- Notice that the new changes did not save

**Comment by NathanCoit** [comment]
Fixed in c3edf9509559a75d8135094cd10efedcd537d070
