### ISSUE TITLE
ISSUE: "V" Button does Nothing as Duck God

### ISSUE THREAD

**Issue by SusanSuY** [NathanCoit/4GP6Capstone#58]
**Issue:** During gameplay as Duck God, the "V" button appears to be clickable, but does nothing when clicked.

**Steps to reproduce:**
- Open game
- Create new game as Duck god
- Click on the "V" button on the bottom-right menu
- Notice that nothing happens

**Comment by NathanCoit** [comment]
Fixed in 3886cefd92f1da2b8ea86d1d648b03abfc04b872
