### ISSUE TITLE
ISSUE: Options Menu is Movable if it is Clicked and Dragged

### ISSUE THREAD

**Issue by SusanSuY** [NathanCoit/4GP6Capstone#60]
**Issue:** The options menu is movable when clicked and dragged.

**Steps to reproduce:**
- Open the game
- Click "Options"
- Click and drag on any area within the Options box
- Notice that the Options menu moves

**Comment by NathanCoit** [comment]
Fixed in c53cb4254ae37fadaef743a6f819728a4f281125
