### ISSUE TITLE
SUGGESTION: Limit the amount of camera movement to the edge of the visible map

### ISSUE THREAD

**Issue by SusanSuY** [NathanCoit/4GP6Capstone#61]
### Context
While in game, I decided to see how big the map was and to explore it, so thus I moved my cursor to one corner of the screen and left it. I noticed that the camera moved infinitely and even off of the map.

### High Level Feature Explanation
Addition of a limit for camera movement to stop at the edges of the map.

## Rationale
This type of infinite camera movement which is not limited is rather undesirable since if I were to AFK and leave the cursor at the corner of the screen, by the time I come back, my camera would be so far off the map that it would be unfeasible to try to return back to my area of interest on the map. This can cause players to have to exit the game in order to return back to their territory, which is an undesirable action that needs to be done as a result of this infinite camera movement.

## System Configuration
This was tested on Windows 10 on 1280x720 resolution in windowed mode.

**Comment by wildingelijah** [comment]
Fixed.
