### ISSUE TITLE
ISSUE: During battle, the Gods are slightly off screen

### ISSUE THREAD

**Issue by SusanSuY** [NathanCoit/4GP6Capstone#62]
### Context
While playing the game and attempting to enter a battle, I noticed that it seemed like there was something on top of the screen that was cut off. I realized that these were the Gods, and that they were not fully visible, therefore, I was unsure if I was missing something graphically important during battle due to the Gods being clipped off on the top of the screen. I also noticed what seemed to be part of some text, but this text was cut off, and thus unreadable.

### Expected Output
During battle, I expect to be able to fully see all elements on the screen, including the Gods.

### Actual Output
During battle, the Gods are cut off at the top of the screen under all resolutions listed in the options of the Configuration window (upon initial game launch). These resolutions include:
- 320x200
- 320x240
- 400x300
- 512x384
- 640x400
- 640x480
- 800x600
- 1024x768
- 1152x864
- 1280x600
- 1280x720
- 1280x768
- 1280x800
- 1360x768
- 1366x768

An image of the issue is displayed below, in which some black text can be very slightly seen, but is completely cutoff, and thus unreadable.
![image](https://user-images.githubusercontent.com/15915128/53035417-5e3cb200-3443-11e9-8093-6cab6f83477d.png)

## Steps to Reproduce
1. Open the game in any resolution.
2. Start the game with any settings for God name and God type.
3. Enter a battle by clicking on another God's village and pressing 'B'.
4. Notice that the Gods are not fully contained in the screen (clipped off at the top), and there is some black text which is also clipped off.

## Appearance of Bug
This bug was seen on all resolutions which are options in the Configuration window (upon initial launch of the game). Some resolutions showed slightly more of the clipped off text than others, but overall, all resolutions had the text clipped off to the extent in which it was unreadable.

### Game Resolution
This was tested on all resolution options available in the game's configuration in both windowed and fullscreen mode.

### System Specifications
- **OS:** Windows 10 Education (Version 1809, OS build 17763.316) 64-bit
- **Processor:** Intel i5-3230M @ 2.60GHz
- **RAM:** 8GB
- **Controller type:** mouse and keyboard

**Comment by wildingelijah** [comment]
Fixed (added ability to pan camera and when unit is selected it centers on it)
