### ISSUE TITLE
SUGGESTION: During battle, add a way of exiting the menu after clicking on a friendly minion

### ISSUE THREAD

**Issue by SusanSuY** [NathanCoit/4GP6Capstone#63]
### Context
Upon entering a battle and attempting to perform actions with my minions, I decided that I did not want to perform actions with my currently selected minion just yet, and would prefer to perform actions with a different minion. However, I was unable to exit the options menu for my currently selected minion, and the minion that I wanted to select was blocked by the options menu. Therefore, I was forced to perform undesirable actions with my currently selected minion as there was no way out of exiting the options menu.

### High Level Feature Explanation
Add a method of exiting out of the options menu upon selecting a minion during battle.

## Rationale
The options menu of the currently selected minion during battle could potentially be blocking another minion that the player wants to select, thus forcing the player to perform undesirable actions in order to get out of the options menu. Such actions can involve clicking on another minion in hopes that their options menu won't block the desired minion, or performing undesirable actions on the currently selected minion in order to make the options menu go away. This can interfere with the player's strategy during combat, and cause player frustration.

## System Configuration
This was tested on Windows 10.

## Suggested Solutions
A suggested solution is that when the player clicks on an area outside of the options menu, the options menu will disappear. I believe that this solution is intuitive and likely desired and expected by most players.

**Comment by wildingelijah** [comment]
Fixed (click away to exit menu).
