### ISSUE TITLE
[Damian] SUGGESTION #3: Add option in battle-phase to "End All"

### ISSUE THREAD

**Issue by DamianAngelone** [NathanCoit/4GP6Capstone#66]
**Targeted Mechanic**
Making it easier and faster to end your turn during combat.

**Suggestion**
Rather than clicking each character and god to end their turn, add a global "End All" button.

**Significance**
This can speed of the length of the battle and eliminate redundant clicks by the user. This will help the flow of your combat sequences.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: Laptop's QWERTY Keyboard

**Comment by wildingelijah** [comment]
Added!
