### ISSUE TITLE
[Damian] BUG #5: Character's Menu is Covered by God

### ISSUE THREAD

**Issue by DamianAngelone** [NathanCoit/4GP6Capstone#68]
**Description**
The battle menu for the character becomes unreadable and unclickable when the character appears in a position for the menu spawns "inside" the god.

**Steps to Reproduce**
- Enter a battle, either manually or by waiting to be attacked
- Move a friendly character near/under either the friendly or enemy god
- Note that the character's menu will now be unclickable, as it is covered by the boss

**Appearance of Bug**
Based on the map layout present in the demo, this bug can occur in all instances of a combat sequence. Maybe in the full game, other grid layouts will not run into this issue.

**Suggested Solutions**
The easiest option would be to either spawn the menu as a UI element rather than a world space GameObject, or fixing the menu to always appear in the bottom corner.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: Laptop's QWERTY Keyboard

**Comment by wildingelijah** [comment]
Fixed.
