### ISSUE TITLE
[Damian] ISSUE #6: God Menu doesn't Close upon Clicking away

### ISSUE THREAD

**Issue by DamianAngelone** [NathanCoit/4GP6Capstone#69]
**Description**
Unlike the characters' menus that disappear upon clicking another character, the god's menu will stay open for the remainder of the turn after being opened at any point.

**Steps to Reproduce**
- Start a battle, either manually or by waiting to be attacked
- Open the god's menu
- Switch focus to another friendly character
- Note that, unlike friendly units, the god's menu remains opened

**Appearance of Bug**
This occurs in all instances of battles, and attempting to find a case where this doesn't occur couldn't be found.

**Suggested Solutions**
Use the same logic that is used on friendly unit menus on the boss' menu as well.

**System Configuration**
- Game tested as windowed (1280 x 600)
- OS: Microsoft Windows 10 (Version 10.0.17134)
- Tested on Laptop: 8GB RAM, Intel Core i5-4210U, 1.70GHz 
- Controller: Laptop's QWERTY Keyboard

**Comment by wildingelijah** [comment]
Fixed.
