### ISSUE TITLE
SUGGESTION: Make selecting units the same for enemies and allies in battle as shoe god.

### ISSUE THREAD

**Issue by KarnvirBining** [NathanCoit/4GP6Capstone#95]
When selecting a unit to move, you must select the actual green object. When selecting a unit to attack you must select the tile on the floor below the red object.  This makes it un-intuitive to play. I suggest making them both select-able or just pick one. I only got to test it as the shoe god so I'd suggest the same for any other gods this applies to.

**Comment by harrilau** [comment]
Similar to #67
