### ISSUE TITLE
ISSUE: Pressing the "V" key locks camera 

### ISSUE THREAD

**Issue by KarnvirBining** [NathanCoit/4GP6Capstone#97]
Pressing the "V" key locks the camera in place until "V" is input again or the player hits "esc". This bug seems to happen to every god aside from the mushroom god. 

Steps:
1. Open new game as any god other than mushroom god
2. press the "V" key
3. Notice that the camera no longer moves up, down, left, or right

**Comment by NathanCoit** [comment]
Fixed in 3886cefd92f1da2b8ea86d1d648b03abfc04b872
