### ISSUE TITLE
ISSUE: Same name can be re-used for same god

### ISSUE THREAD

**Issue by KarnvirBining** [NathanCoit/4GP6Capstone#98]
A new game can be started using an already saved name and the same god. 

Steps
1. Start a new game as shoe god with "your name here"
2. Save the game 
3. Exit to main menu 
4. Repeat steps 1-3
5. Go to load game and notice repeated files and names (only differentiating factor is time of save)

**Comment by NathanCoit** [comment]
Currently intended as there is no real way to distinguish saves other than save time in this case without cluttering save file UI. Implementing option to overwrite or create a new save should lower total number of save files and make distinguishing between easier.
