### ISSUE TITLE
SUGGESTION: Camera zoom out functionality 

### ISSUE THREAD

**Issue by KarnvirBining** [NathanCoit/4GP6Capstone#99]
The camera currently stops zooming out at a certain point. This doesn't allow the entire map to be visible and when the game gets more advanced the screen becomes very crowded (max zoom at a tier two stage shown below). Some ability to snap to a fully zoomed out view (Key binding) or the ability to scroll out and see the whole map would make this much easier to manage and look at. 

![scrolling_bug10](https://user-images.githubusercontent.com/9940441/50439074-9b127f80-08be-11e9-86cc-2ba7cc4ab7a8.JPG)

**Comment by wildingelijah** [comment]
Fixed max FOV so that players can zoom out much further now. Also scaled down buildings to make view seem much greater
